### PR TITLE
Backend api

### PR DESCRIPTION
**Pull request by mc-lojek**
CRUD operations for sensors and measurements
Docker compose and dockerfile for backend .Net app
Rabbitmq + mongodb instances configured

- - -
This change is [Reviewable](https://reviewable.io/reviews/haichangsi/monitoring-iot-devices/1)

### CODE REVIEW

**Review by haichangsi — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/haichangsi/monitoring-iot-devices/1)* status: 0 of 24 files reviewed, all discussions resolved (waiting on @mc-lojek)

**Review by mc-lojek — COMMENTED** [review]
> Reviewed 24 of 24 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/haichangsi/monitoring-iot-devices/1)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mc-lojek)

**Comment by mc-lojek** [comment]
ok

**Review by haichangsi — CHANGES_REQUESTED** [review]
warn: Microsoft.AspNetCore.HttpsPolicy.HttpsRedirectionMiddleware[3]
docker-iot-api-1        |       Failed to determine the https port for redirect.
fix? : https://stackoverflow.com/questions/51385671/failed-to-determine-the-https-port-for-redirect-in-docker

> Reviewed 24 of 24 files at r1.
> *[Reviewable](https://reviewable.io/reviews/haichangsi/monitoring-iot-devices/1#-:-NG6-ZwR2IQxdnoOuDBf:btydhwm)* status: all files reviewed, 17 unresolved discussions (waiting on @mc-lojek)

___
*[`back/appsettings.json` line 3 at r1](https://reviewable.io/reviews/haichangsi/monitoring-iot-devices/1#-NG3MuMe49C173Axx-Ts:-NG3MuMe49C173Axx-Tt:b-bvzc8n) ([raw file](https://github.com/haichangsi/monitoring-iot-devices/blob/765266c7d8dd51550112989e8e7adcca45b310ca/back/appsettings.json#L3)):*
> ```JSON
> {
>   "IotDatabase": {
>     "ConnectionString": "mongodb://dotnetowiec:lubie.Net!@mongo:27017/",
> ```

ej ja dobrze rozumiem, że dajemy hasło plaintextem? xd proponowałbym plik konfiguracyjny z takimi danymi i w kontekście projektu i tak go spushujemy na repo, ale można pokazać i zaznaczyć, że zdajemy sobie sprawę z problemu i normalnie to dodatkowy wpis do gitignore np.
___
*[`back/appsettings.Development.json` line 3 at r1](https://reviewable.io/reviews/haichangsi/monitoring-iot-devices/1#-NG3QLd53fGq-Lau6N3n:-NG3QLd6BE8fRNPcYEpV:b3kqx) ([raw file](https://github.com/haichangsi/monitoring-iot-devices/blob/765266c7d8dd51550112989e8e7adcca45b310ca/back/appsettings.Development.json#L3)):*
> ```JSON
> {
>   "IotDatabase": {
>     "ConnectionString": "mongodb://dotnetowiec:lubie.Net!@localhost:27017/",
> ```

.
___
*[`back/Program.cs` line 20 at r1](https://reviewable.io/reviews/haichangsi/monitoring-iot-devices/1#-NG3RPdIEuKbcMUvye3D:-NG3RPdJ3P5nPHnMJtq9:b-2m8801) ([raw file](https://github.com/haichangsi/monitoring-iot-devices/blob/765266c7d8dd51550112989e8e7adcca45b310ca/back/Program.cs#L20)):*
> ```Smalltalk
>         }
>     }
> }
> ```

dodaj jak mozesz jedna pustą linię na końcu, prościej potem rozwijać, dużo łatwiej w vimie zwykłym skrótów używać, plus taka konwencja, sory za czepianie się xd
___
*[`back/Startup.cs` line 58 at r1](https://reviewable.io/reviews/haichangsi/monitoring-iot-devices/1#-NG3R_k_EkZ3CMQKgWbR:-NG3R_k_EkZ3CMQKgWbS:b3kqx) ([raw file](https://github.com/haichangsi/monitoring-iot-devices/blob/765266c7d8dd51550112989e8e7adcca45b310ca/back/Startup.cs#L58)):*
> ```Smalltalk
>         }
>     }
> }
> ```

.
___
*[`back/.idea/.idea.dot.dir/.idea/.name` line 1 at r1](https://reviewable.io/reviews/haichangsi/monitoring-iot-devices/1#-NG3RhC_01PDKTwp-UIe:-NG3RhC_01PDKTwp-UIf:b3kqx) ([raw file](https://github.com/haichangsi/monitoring-iot-devices/blob/765266c7d8dd51550112989e8e7adcca45b310ca/back/.idea/.idea.dot.dir/.idea/.name#L1)):*
> ```
> dot
> ```

.
___
*[`back/.idea/.idea.dot.dir/.idea/encodings.xml` line 4 at r1](https://reviewable.io/reviews/haichangsi/monitoring-iot-devices/1#-NG3RdQH-TO0wclWoNPw:-NG3RdQH-TO0wclWoNPx:b3kqx) ([raw file](https://github.com/haichangsi/monitoring-iot-devices/blob/765266c7d8dd51550112989e8e7adcca45b310ca/back/.idea/.idea.dot.dir/.idea/encodings.xml#L4)):*
> ```XML
> <project version="4">
>   <component name="Encoding" addBOMForNewFiles="with BOM under Windows, with no BOM otherwise" />
> </project>
> ```

.
___
*[`back/.idea/.idea.dot.dir/.idea/indexLayout.xml` line 8 at r1](https://reviewable.io/reviews/haichangsi/monitoring-iot-devices/1#-NG3Re34B2gKBQkmU5QH:-NG3Re34B2gKBQkmU5QI:b3kqx) ([raw file](https://github.com/haichangsi/monitoring-iot-devices/blob/765266c7d8dd51550112989e8e7adcca45b310ca/back/.idea/.idea.dot.dir/.idea/indexLayout.xml#L8)):*
> ```XML
>     <explicitExcludes />
>   </component>
> </project>
> ```

.
___
*[`back/.idea/.idea.dot.dir/.idea/vcs.xml` line 6 at r1](https://reviewable.io/reviews/haichangsi/monitoring-iot-devices/1#-NG3RfQZ5Tsg9MJI8ncz:-NG3RfQZ5Tsg9MJI8nd-:b3kqx) ([raw file](https://github.com/haichangsi/monitoring-iot-devices/blob/765266c7d8dd51550112989e8e7adcca45b310ca/back/.idea/.idea.dot.dir/.idea/vcs.xml#L6)):*
> ```XML
>     <mapping directory="$PROJECT_DIR$/.." vcs="Git" />
>   </component>
> </project>
> ```

.
___
*[`back/Controllers/IotController.cs` line 75 at r1](https://reviewable.io/reviews/haichangsi/monitoring-iot-devices/1#-NG3RvHNCtCjA9MwHuN1:-NG3RvHNCtCjA9MwHuN2:b3kqx) ([raw file](https://github.com/haichangsi/monitoring-iot-devices/blob/765266c7d8dd51550112989e8e7adcca45b310ca/back/Controllers/IotController.cs#L75)):*
> ```Smalltalk
>         }
>     }
> }
> ```

.
___
*[`back/Controllers/SensorController.cs` line 75 at r1](https://reviewable.io/reviews/haichangsi/monitoring-iot-devices/1#-NG3TBKDBc9x1o4uaYpr:-NG3TBKDBc9x1o4uaYps:b3kqx) ([raw file](https://github.com/haichangsi/monitoring-iot-devices/blob/765266c7d8dd51550112989e8e7adcca45b310ca/back/Controllers/SensorController.cs#L75)):*
> ```Smalltalk
>         }
>     }
> }
> ```

.
___
*[`back/Models/IotDatabaseSettings.cs` line 12 at r1](https://reviewable.io/reviews/haichangsi/monitoring-iot-devices/1#-NG3TIy9Ba3db6LhUMCq:-NG3TIy9Ba3db6LhUMCr:b3kqx) ([raw file](https://github.com/haichangsi/monitoring-iot-devices/blob/765266c7d8dd51550112989e8e7adcca45b310ca/back/Models/IotDatabaseSettings.cs#L12)):*
> ```Smalltalk
>         public string SensorsCollectionName { get; set; } = null!;
>     }
> }
> ```

.
___
*[`back/Models/Measurement.cs` line 11 at r1](https://reviewable.io/reviews/haichangsi/monitoring-iot-devices/1#-NG3TZWP0Vm-NpaGWDMw:-NG3TZWP0Vm-NpaGWDMx:becni6b) ([raw file](https://github.com/haichangsi/monitoring-iot-devices/blob/765266c7d8dd51550112989e8e7adcca45b310ca/back/Models/Measurement.cs#L11)):*
> ```Smalltalk
>         [BsonId]
>         [BsonRepresentation(BsonType.ObjectId)]
>         public string? Id { get; set; }
> ```

w jakim przypadku id pomiaru może być nullem? i sory za bycie dziwnym, ale chyba camelCase jest konwencja, więc może Id -> id xdd
___
*[`back/Models/Measurement.cs` line 14 at r1](https://reviewable.io/reviews/haichangsi/monitoring-iot-devices/1#-NG3Tq8iEqGwJLBapqsS:-NG3Tq8iEqGwJLBapqsT:b-21jww5) ([raw file](https://github.com/haichangsi/monitoring-iot-devices/blob/765266c7d8dd51550112989e8e7adcca45b310ca/back/Models/Measurement.cs#L14)):*
> ```Smalltalk
> 
>         public float value { get; set; } = 0.0f;
>         public string? sensorId { get; set; }
> ```

albo sensora?
___
*[`back/Models/Measurement.cs` line 18 at r1](https://reviewable.io/reviews/haichangsi/monitoring-iot-devices/1#-NG3TJzGD6z9Yrd79yWI:-NG3TJzGD6z9Yrd79yWJ:b3kqx) ([raw file](https://github.com/haichangsi/monitoring-iot-devices/blob/765266c7d8dd51550112989e8e7adcca45b310ca/back/Models/Measurement.cs#L18)):*
> ```Smalltalk
>         public string unit { get; set; }
>     }
> }
> ```

.
___
*[`docker/build-and-run.sh` line 1 at r1](https://reviewable.io/reviews/haichangsi/monitoring-iot-devices/1#-NG6-mNa6sJJUxYw9tyD:-NG6-mNa6sJJUxYw9tyE:b-ahfa3a) ([raw file](https://github.com/haichangsi/monitoring-iot-devices/blob/765266c7d8dd51550112989e8e7adcca45b310ca/docker/build-and-run.sh#L1)):*
> ```Shell
> docker build -t iot-api -f ./api-dockerfile ../back
> ```

u mnie zadziałało dopiero jak dałem ' -f ./Dockerfile ' mimo że defaultowo powinno łapać, chyba że masz innego dockerfile(jak sugeruje komenda xd), którego nie wrzuciłeś i problemy się rozwiążą xD



_Code quote:_
```Shell
-f ./api-dockerfile
```
___
*[`docker/Dockerfile` line 1 at r1](https://reviewable.io/reviews/haichangsi/monitoring-iot-devices/1#-NG6-CV-4KzgQVf4fFSy:-NG6-CV-4KzgQVf4fFSz:b-dubfia) ([raw file](https://github.com/haichangsi/monitoring-iot-devices/blob/765266c7d8dd51550112989e8e7adcca45b310ca/docker/Dockerfile#L1)):*
> ```Dockerfile
> FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS runtime
> ```

wyrzuciło mi, że chce 5.0



_Code quote:_
```Dockerfile
6.0
```
___
*[`docker/README.md` line 4 at r1](https://reviewable.io/reviews/haichangsi/monitoring-iot-devices/1#-NG60DXb-RG3cd1EdB1W:-NG60DXb-RG3cd1EdB1X:b-qzn9pb) ([raw file](https://github.com/haichangsi/monitoring-iot-devices/blob/765266c7d8dd51550112989e8e7adcca45b310ca/docker/README.md#L4)):*
> ```Markdown
> Aby odpalić całą kompozycję dockerową:
>  1. Buildujemy aktualną wersję projektu .net `dotnet publish -c Release -o published`
>  2. Odpalamy skrypt build-and-run stawiający kompozycję (w zależności od systemu .sh lub .bat) `./build-and-run.sh`
> ```

docker instalowany z paczki ma w sobie docker compose, ale potrzebuje sudo wcześniej, warto pewnie dodać, że docker compose to nowa wersja docker-compose i żeby tego nie instalować, zanczy nikt tego projektu nigdy nie będzie odpalał, ale tak tylko piszę bo miałem problem xd

**Review by mc-lojek — COMMENTED** [review]
:lgtm: nie wiem co tu napisac

> Reviewed 7 of 11 files at r2, 1 of 4 files at r3, 5 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/haichangsi/monitoring-iot-devices/1#-:-NFsYrvl5I2ImlOCaPHU:b-jwivfn)* status: all files reviewed, 17 unresolved discussions (waiting on @haichangsi)

___
*[`back/appsettings.json` line 3 at r1](https://reviewable.io/reviews/haichangsi/monitoring-iot-devices/1#-NG3MuMe49C173Axx-Ts:-NGJZphO4ROr_Xd2ELYt:b-9e2c03) ([raw file](https://github.com/haichangsi/monitoring-iot-devices/blob/765266c7d8dd51550112989e8e7adcca45b310ca/back/appsettings.json#L3)):*
<details><summary><i>Previously, haichangsi (Kacper Stefanski) wrote…</i></summary><blockquote>

ej ja dobrze rozumiem, że dajemy hasło plaintextem? xd proponowałbym plik konfiguracyjny z takimi danymi i w kontekście projektu i tak go spushujemy na repo, ale można pokazać i zaznaczyć, że zdajemy sobie sprawę z problemu i normalnie to dodatkowy wpis do gitignore np.
</blockquote></details>

ustalone że olewamy
___
*[`back/appsettings.Development.json` line 3 at r1](https://reviewable.io/reviews/haichangsi/monitoring-iot-devices/1#-NG3QLd53fGq-Lau6N3n:-NGJb2UVCLuFsJ4VhzWW:b32wpe) ([raw file](https://github.com/haichangsi/monitoring-iot-devices/blob/765266c7d8dd51550112989e8e7adcca45b310ca/back/appsettings.Development.json#L3)):*
<details><summary><i>Previously, haichangsi (Kacper Stefanski) wrote…</i></summary><blockquote>

.
</blockquote></details>

jw
___
*[`back/Program.cs` line 20 at r1](https://reviewable.io/reviews/haichangsi/monitoring-iot-devices/1#-NG3RPdIEuKbcMUvye3D:-NGJYg9_AkngilzyF9mj:bs7wumb) ([raw file](https://github.com/haichangsi/monitoring-iot-devices/blob/765266c7d8dd51550112989e8e7adcca45b310ca/back/Program.cs#L20)):*
<details><summary><i>Previously, haichangsi (Kacper Stefanski) wrote…</i></summary><blockquote>

dodaj jak mozesz jedna pustą linię na końcu, prościej potem rozwijać, dużo łatwiej w vimie zwykłym skrótów używać, plus taka konwencja, sory za czepianie się xd
</blockquote></details>

Done.
___
*[`back/Startup.cs` line 58 at r1](https://reviewable.io/reviews/haichangsi/monitoring-iot-devices/1#-NG3R_k_EkZ3CMQKgWbR:-NGJYk6Y236kPcUe9cyh:b-896fix) ([raw file](https://github.com/haichangsi/monitoring-iot-devices/blob/765266c7d8dd51550112989e8e7adcca45b310ca/back/Startup.cs#L58)):*
<details><summary><i>Previously, haichangsi (Kacper Stefanski) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[`back/.idea/.idea.dot.dir/.idea/.name` line 1 at r1](https://reviewable.io/reviews/haichangsi/monitoring-iot-devices/1#-NG3RhC_01PDKTwp-UIe:-NGJYkqs9-agAUaD_Z7A:b-896fix) ([raw file](https://github.com/haichangsi/monitoring-iot-devices/blob/765266c7d8dd51550112989e8e7adcca45b310ca/back/.idea/.idea.dot.dir/.idea/.name#L1)):*
<details><summary><i>Previously, haichangsi (Kacper Stefanski) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[`back/.idea/.idea.dot.dir/.idea/encodings.xml` line 4 at r1](https://reviewable.io/reviews/haichangsi/monitoring-iot-devices/1#-NG3RdQH-TO0wclWoNPw:-NGJYmPr90JFwhhE8qMo:b-896fix) ([raw file](https://github.com/haichangsi/monitoring-iot-devices/blob/765266c7d8dd51550112989e8e7adcca45b310ca/back/.idea/.idea.dot.dir/.idea/encodings.xml#L4)):*
<details><summary><i>Previously, haichangsi (Kacper Stefanski) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[`back/.idea/.idea.dot.dir/.idea/indexLayout.xml` line 8 at r1](https://reviewable.io/reviews/haichangsi/monitoring-iot-devices/1#-NG3Re34B2gKBQkmU5QH:-NGJYnAY2qwMN_2owXq9:b-896fix) ([raw file](https://github.com/haichangsi/monitoring-iot-devices/blob/765266c7d8dd51550112989e8e7adcca45b310ca/back/.idea/.idea.dot.dir/.idea/indexLayout.xml#L8)):*
<details><summary><i>Previously, haichangsi (Kacper Stefanski) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[`back/.idea/.idea.dot.dir/.idea/vcs.xml` line 6 at r1](https://reviewable.io/reviews/haichangsi/monitoring-iot-devices/1#-NG3RfQZ5Tsg9MJI8ncz:-NGJYnowBAvJVKLMFNLI:b-896fix) ([raw file](https://github.com/haichangsi/monitoring-iot-devices/blob/765266c7d8dd51550112989e8e7adcca45b310ca/back/.idea/.idea.dot.dir/.idea/vcs.xml#L6)):*
<details><summary><i>Previously, haichangsi (Kacper Stefanski) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[`back/Controllers/IotController.cs` line 75 at r1](https://reviewable.io/reviews/haichangsi/monitoring-iot-devices/1#-NG3RvHNCtCjA9MwHuN1:-NGJYohBCI_6tZdcSMh5:b-896fix) ([raw file](https://github.com/haichangsi/monitoring-iot-devices/blob/765266c7d8dd51550112989e8e7adcca45b310ca/back/Controllers/IotController.cs#L75)):*
<details><summary><i>Previously, haichangsi (Kacper Stefanski) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[`back/Controllers/SensorController.cs` line 75 at r1](https://reviewable.io/reviews/haichangsi/monitoring-iot-devices/1#-NG3TBKDBc9x1o4uaYpr:-NGJYsK29LZ0wRcP7XsF:b-896fix) ([raw file](https://github.com/haichangsi/monitoring-iot-devices/blob/765266c7d8dd51550112989e8e7adcca45b310ca/back/Controllers/SensorController.cs#L75)):*
<details><summary><i>Previously, haichangsi (Kacper Stefanski) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[`back/Models/IotDatabaseSettings.cs` line 12 at r1](https://reviewable.io/reviews/haichangsi/monitoring-iot-devices/1#-NG3TIy9Ba3db6LhUMCq:-NGJYsswCexYr19w_FQB:b-896fix) ([raw file](https://github.com/haichangsi/monitoring-iot-devices/blob/765266c7d8dd51550112989e8e7adcca45b310ca/back/Models/IotDatabaseSettings.cs#L12)):*
<details><summary><i>Previously, haichangsi (Kacper Stefanski) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[`back/Models/Measurement.cs` line 11 at r1](https://reviewable.io/reviews/haichangsi/monitoring-iot-devices/1#-NG3TZWP0Vm-NpaGWDMw:-NGJVfoD0yLm0W_NObt0:b2anu2) ([raw file](https://github.com/haichangsi/monitoring-iot-devices/blob/765266c7d8dd51550112989e8e7adcca45b310ca/back/Models/Measurement.cs#L11)):*
<details><summary><i>Previously, haichangsi (Kacper Stefanski) wrote…</i></summary><blockquote>

w jakim przypadku id pomiaru może być nullem? i sory za bycie dziwnym, ale chyba camelCase jest konwencja, więc może Id -> id xdd
</blockquote></details>

No w normalnym jezyku powinien byc camelCase, tak jak mowisz, ale oficjalne wiki m$ sugeruje żeby zmienne z wilkiej litery zaczynać, także zmienię wszędzie na wielką dla ujednolicenia. No i ten nullable też jest wzięty z dokumentacji, prawdopodobnie dlatego że id jest tworzone automatycznie w momencie dodania do bazy, więc inicjalnie jest nullem i wrzuca prze refleksje czy coś.
Źródło: https://learn.microsoft.com/en-us/aspnet/core/tutorials/first-mongo-app?view=aspnetcore-6.0&tabs=visual-studio
___
*[`back/Models/Measurement.cs` line 14 at r1](https://reviewable.io/reviews/haichangsi/monitoring-iot-devices/1#-NG3Tq8iEqGwJLBapqsS:-NGJYvQw9lLfad2xRTga:br4q2ce) ([raw file](https://github.com/haichangsi/monitoring-iot-devices/blob/765266c7d8dd51550112989e8e7adcca45b310ca/back/Models/Measurement.cs#L14)):*
<details><summary><i>Previously, haichangsi (Kacper Stefanski) wrote…</i></summary><blockquote>

albo sensora?
</blockquote></details>

to samo co u gory
___
*[`back/Models/Measurement.cs` line 18 at r1](https://reviewable.io/reviews/haichangsi/monitoring-iot-devices/1#-NG3TJzGD6z9Yrd79yWI:-NGJYxx15vRYgosA2A7H:b-896fix) ([raw file](https://github.com/haichangsi/monitoring-iot-devices/blob/765266c7d8dd51550112989e8e7adcca45b310ca/back/Models/Measurement.cs#L18)):*
<details><summary><i>Previously, haichangsi (Kacper Stefanski) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[`docker/build-and-run.sh` line 1 at r1](https://reviewable.io/reviews/haichangsi/monitoring-iot-devices/1#-NG6-mNa6sJJUxYw9tyD:-NGJYyyy-4CNOFU-odp2:b-4n2o9k) ([raw file](https://github.com/haichangsi/monitoring-iot-devices/blob/765266c7d8dd51550112989e8e7adcca45b310ca/docker/build-and-run.sh#L1)):*
<details><summary><i>Previously, haichangsi (Kacper Stefanski) wrote…</i></summary><blockquote>

u mnie zadziałało dopiero jak dałem ' -f ./Dockerfile ' mimo że defaultowo powinno łapać, chyba że masz innego dockerfile(jak sugeruje komenda xd), którego nie wrzuciłeś i problemy się rozwiążą xD
</blockquote></details>

celowo nazwalem ten plik api-dockerfile zeby trzymac wszystkie dockerfile w jednym katalogu a nie kazdy w innym miejscu. u mnie na windzie działało :/
___
*[`docker/Dockerfile` line 1 at r1](https://reviewable.io/reviews/haichangsi/monitoring-iot-devices/1#-NG6-CV-4KzgQVf4fFSy:-NGJWRss-ptX4qeAO-mJ:b-66h4ol) ([raw file](https://github.com/haichangsi/monitoring-iot-devices/blob/765266c7d8dd51550112989e8e7adcca45b310ca/docker/Dockerfile#L1)):*
<details><summary><i>Previously, haichangsi (Kacper Stefanski) wrote…</i></summary><blockquote>

wyrzuciło mi, że chce 5.0
</blockquote></details>

Racja, powinno być 5.0, na ostatnią chwilę to poprawiałem bo doczytałem w instrukcji że ma być 5.0 no i tutaj musiałem przeoczyć.
___
*[`docker/README.md` line 4 at r1](https://reviewable.io/reviews/haichangsi/monitoring-iot-devices/1#-NG60DXb-RG3cd1EdB1W:-NGJZFCz2Vg9ON0ZiDym:b-896fix) ([raw file](https://github.com/haichangsi/monitoring-iot-devices/blob/765266c7d8dd51550112989e8e7adcca45b310ca/docker/README.md#L4)):*
<details><summary><i>Previously, haichangsi (Kacper Stefanski) wrote…</i></summary><blockquote>

docker instalowany z paczki ma w sobie docker compose, ale potrzebuje sudo wcześniej, warto pewnie dodać, że docker compose to nowa wersja docker-compose i żeby tego nie instalować, zanczy nikt tego projektu nigdy nie będzie odpalał, ale tak tylko piszę bo miałem problem xd
</blockquote></details>

Done.

**Review by mc-lojek — COMMENTED** [review]
> Reviewed 6 of 6 files at r5, 5 of 5 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/haichangsi/monitoring-iot-devices/1)* status: all files reviewed, 18 unresolved discussions (waiting on @haichangsi and @mc-lojek)

___
*[`back/.idea/.idea.dot.dir/.idea/.gitignore` line 0 at r5](https://reviewable.io/reviews/haichangsi/monitoring-iot-devices/1#-NGg7qYm3UFgsOH9kJt-:-NGg7qYm3UFgsOH9kJt0:b318asz) ([raw file](https://github.com/haichangsi/monitoring-iot-devices/blob/3e9fafbd7eb43d77cd14ec9830fed7dd6ab27a4c/back/.idea/.idea.dot.dir/.idea/.gitignore#L0)):*
niepotrzebny plik, usuwam z gita
___
*[`back/.idea/.idea.dot.dir/.idea/.name` line 1 at r1](https://reviewable.io/reviews/haichangsi/monitoring-iot-devices/1#-NG3RhC_01PDKTwp-UIe:-NGg7y0384Zqril2cyCt:bc67dcn) ([raw file](https://github.com/haichangsi/monitoring-iot-devices/blob/765266c7d8dd51550112989e8e7adcca45b310ca/back/.idea/.idea.dot.dir/.idea/.name#L1)):*
<details><summary><i>Previously, mc-lojek wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Niepotrzebny plik, usuwam z gita
___
*[`back/.idea/.idea.dot.dir/.idea/encodings.xml` line 4 at r1](https://reviewable.io/reviews/haichangsi/monitoring-iot-devices/1#-NG3RdQH-TO0wclWoNPw:-NGg8CrV5BFsWdaU8LwN:bc67dcn) ([raw file](https://github.com/haichangsi/monitoring-iot-devices/blob/765266c7d8dd51550112989e8e7adcca45b310ca/back/.idea/.idea.dot.dir/.idea/encodings.xml#L4)):*
<details><summary><i>Previously, mc-lojek wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Niepotrzebny plik, usuwam z gita
___
*[`back/.idea/.idea.dot.dir/.idea/indexLayout.xml` line 8 at r1](https://reviewable.io/reviews/haichangsi/monitoring-iot-devices/1#-NG3Re34B2gKBQkmU5QH:-NGg8FC42jq4RydPG7wO:bc67dcn) ([raw file](https://github.com/haichangsi/monitoring-iot-devices/blob/765266c7d8dd51550112989e8e7adcca45b310ca/back/.idea/.idea.dot.dir/.idea/indexLayout.xml#L8)):*
<details><summary><i>Previously, mc-lojek wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Niepotrzebny plik, usuwam z gita
___
*[`back/.idea/.idea.dot.dir/.idea/vcs.xml` line 6 at r1](https://reviewable.io/reviews/haichangsi/monitoring-iot-devices/1#-NG3RfQZ5Tsg9MJI8ncz:-NGg8HUK2xi5zoCOD2Sc:bc67dcn) ([raw file](https://github.com/haichangsi/monitoring-iot-devices/blob/765266c7d8dd51550112989e8e7adcca45b310ca/back/.idea/.idea.dot.dir/.idea/vcs.xml#L6)):*
<details><summary><i>Previously, mc-lojek wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Niepotrzebny plik, usuwam z gita

**Review by haichangsi — APPROVED** [review]
:lgtm_strong: 

> Reviewed 7 of 11 files at r2, 5 of 5 files at r4, 6 of 6 files at r5, 5 of 5 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/haichangsi/monitoring-iot-devices/1#-:-NGgcTAR1L-XlvMpTvjL:b-uwkowd)* status: all files reviewed, 1 unresolved discussion (waiting on @mc-lojek)

**Review by haichangsi — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/haichangsi/monitoring-iot-devices/1)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mc-lojek)

___
*[`back/.idea/.idea.dot.dir/.idea/.gitignore` line  at r5](https://reviewable.io/reviews/haichangsi/monitoring-iot-devices/1#-NGg7qYm3UFgsOH9kJt-:-NGgcpfl3GYZOdRj7jWT:bb6zl5l) ([raw file](https://github.com/haichangsi/monitoring-iot-devices/blob/3e9fafbd7eb43d77cd14ec9830fed7dd6ab27a4c/back/.idea/.idea.dot.dir/.idea/.gitignore#L)):*
<details><summary><i>Previously, mc-lojek wrote…</i></summary><blockquote>

niepotrzebny plik, usuwam z gita
</blockquote></details>

Lgtm

**Pull request merged**
